In [1]:
import numpy as np

In [2]:
def generate_matrix(n, m, min_value=0, max_value=9):
    try:
        return np.random.randint(min_value, max_value+1, (n, m))
    except Exception as e:
        return e

def check(A, B):
    try:
        if len(A[0]) == len(B):
            return True
        else:
            return False
    except Exception as e:
        print(f'Exception: {e}')
        return False
    

#### __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

In [3]:
# а)

A = generate_matrix(4, 2)
B = generate_matrix(4, 2)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[1 8]
 [8 4]
 [5 3]
 [8 8]]

B:
[[3 3]
 [9 8]
 [1 6]
 [1 3]]

Произведение матриц A x B не определено.

Произведение матриц A x B не определено.



In [4]:
# б)

A = generate_matrix(2, 5)
B = generate_matrix(5, 3)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[1 1 4 2 8]
 [2 9 0 7 4]]

B:
[[5 3 7]
 [0 8 0]
 [4 1 5]
 [2 3 0]
 [9 5 9]]

A x B:
[[ 97  61  99]
 [ 60 119  50]]

Произведение матриц A x B не определено.



In [5]:
# в)

A = generate_matrix(8, 3)
B = generate_matrix(3, 8)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[9 7 6]
 [1 7 8]
 [1 1 6]
 [1 4 1]
 [8 5 6]
 [1 6 1]
 [5 6 1]
 [6 9 1]]

B:
[[2 5 5 4 0 5 6 3]
 [1 3 2 9 2 0 2 8]
 [8 8 6 6 3 8 3 8]]

A x B:
[[ 73 114  95 135  32  93  86 131]
 [ 73  90  67 115  38  69  44 123]
 [ 51  56  43  49  20  53  26  59]
 [ 14  25  19  46  11  13  17  43]
 [ 69 103  86 113  28  88  76 112]
 [ 16  31  23  64  15  13  21  59]
 [ 24  51  43  80  15  33  45  71]
 [ 29  65  54 111  21  38  57  98]]

B x A:
[[ 85 163 100]
 [ 97 160  73]
 [187 295 191]]



In [6]:
# г)

A = generate_matrix(4, 4)
B = generate_matrix(4, 4)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[6 5 6 8]
 [0 5 9 8]
 [1 2 6 3]
 [4 6 4 0]]

B:
[[8 3 6 4]
 [0 8 1 9]
 [0 3 8 4]
 [7 5 0 1]]

A x B:
[[104 116  89 101]
 [ 56 107  77  89]
 [ 29  52  56  49]
 [ 32  72  62  86]]

B x A:
[[ 70  91 127 106]
 [ 37  96 114  67]
 [ 24  55  91  48]
 [ 46  66  91  96]]



#### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [7]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

print(f'A + B:\n{A + B}\n')
print(f'A x B:\n{np.dot(A, B)}\n')
print(f'B x A:\n{np.dot(B, A)}\n')


A:
[[ 1 -2]
 [ 3  0]]

B:
[[ 4 -1]
 [ 0  5]]

A + B:
[[ 5 -3]
 [ 3  5]]

A x B:
[[  4 -11]
 [ 12  -3]]

B x A:
[[ 1 -8]
 [15  0]]



#### __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [8]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')
print(f'C:\n{C}\n')

print(f'3A - 2B + 4C:\n{3 * A - 2 * B + 4 * C}\n')


A:
[[ 1  7]
 [ 3 -6]]

B:
[[ 0  5]
 [ 2 -1]]

C:
[[ 2 -4]
 [ 1  1]]

3A - 2B + 4C:
[[ 11  -5]
 [  9 -12]]



#### __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [9]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'A:\n{A}\n')
print(f'A.T:\n{A.T}\n')

print(f'A x A.T:\n{np.dot(A, A.T)}\n')
print(f'A.T x A:\n{np.dot(A.T, A)}\n')


A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

A.T:
[[ 4  5  2]
 [ 1 -2  3]]

A x A.T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A.T x A:
[[45  0]
 [ 0 14]]



#### __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [10]:
def generate_array(n, m, min_value=0, max_value=9):
    try:
        return [[np.random.randint(min_value, max_value+1) for _ in range(m)] for _ in range(n)]
    except Exception as e:
        return e

def matrix_product(A, B):
    try:
        C = generate_array(len(A), len(B[0]), 0, 0)
        for i in range(len(A)):  
            for j in range(len(B[0])): 
                for k in range(len(B)): 
                    C[i][j] += A[i][k] * B[k][j]
        return C
    except Exception as e:
        return e


In [11]:
n, m, k = 2, 4, 2

A = generate_array(n, m)
B = generate_array(m, k)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'Trial(A x B):\n{matrix_product(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')

if check(A, B):
    print(f'Check(A x B):\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')


A:
[[0, 4, 8, 2], [3, 7, 4, 6]]

B:
[[8, 4], [9, 7], [7, 7], [1, 4]]

Trial(A x B):
[[94, 92], [121, 113]]

Check(A x B):
[[ 94  92]
 [121 113]]

