In [1]:
import numpy as np
import math
import copy

In [2]:
def matrix_determinant_2x2_3x3(A):
    try:
        if len(A) == len(A[0]):
            if len(A) == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det
            elif len(A) == 3:
                det = (
                    A[0][0] * A[1][1] * A[2][2] +
                    A[0][1] * A[1][2] * A[2][0] +
                    A[0][2] * A[1][0] * A[2][1] -
                    A[0][2] * A[1][1] * A[2][0] -
                    A[0][1] * A[1][0] * A[2][2] -
                    A[0][0] * A[1][2] * A[2][1]
                )
                return det
            else:
                return 'Only 2x2 or 3x3 matricies'
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

#### __1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [3]:
# а)

x = math.pi / 4

A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Trial(det(A)): 1.0000000000000002

Check(det(A)): 1.0



In [4]:
# б)

A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[4 2 3]
 [0 5 1]
 [0 0 9]]

Trial(det(A)): 180

Check(det(A)): 180.0



In [5]:
# в)

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trial(det(A)): 0

Check(det(A)): -9.51619735392994e-16



#### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

In [6]:
A = np.array([[1, -2], [1, 2]])

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0



а) $det(A^{2})$:

$det(A) = 4$<br>

$A^{2}$ = $A x A$<br>
$det(A x B)$ = $det(A) * det(B)$<br>
$det(A^{2})$ = $det(A x A)$ = $det(A) * det(A)$<br>
$det(A^{2})$ = $4 * 4$ = $16$<br>

In [7]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A^2:\n{np.dot(A, A)}\n')
print(f'det(A^2): {np.linalg.det(np.dot(A, A))}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

A^2:
[[-1 -6]
 [ 3  2]]

det(A^2): 16.000000000000007



б) $det(A^{T})$:

$det(A) = 4$<br>

$det(A)$ = $det(A^{T})$<br>
$det(A^{T})$ = $det(A)$ = $4$<br>

In [8]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A:\n{A.T}\n')
print(f'det(A.T): {np.linalg.det(A.T)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

A:
[[ 1  1]
 [-2  2]]

det(A.T): 4.0



в) $det(2A)$:

$det(A) = 4$<br>

$det(kA)$ = $k^{n}det(A)$, где n - кол-во строк (столбцов) квадратной матрицы A размера n x n<br>
$det(2A)$ = $k^{n}det(A)$ = $2^{n} * 4$ = $2^{n+2}$<br>

In [9]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'2A:\n{np.dot(2, A)}\n')
print(f'det(2A): {2**(A.shape[0] + 2)}\n')
print(f'det(2A): {np.linalg.det(2 * A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

2A:
[[ 2 -4]
 [ 2  4]]

det(2A): 16

det(2A): 15.999999999999998



#### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

1) Если $det(A) = 0$, то матрица A вырождена.<br>
2) Если, как минимум, две строки матрицы A линейно зависимы, то матрица A вырождена.<br>

In [10]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'A:\n{A}\n')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]



In [11]:
# 1)

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det( A)}\n')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

det(A): 0.0



In [12]:
# 2)

print(f'A:\n{A}\n')
print(f'Умножим первую строку матрицы A на -2:')
print(f'-2{A[0]} = {A[1]}\n')
print(f'В результате умножения получаем вторую строку матрицы A:')
print(f'{-2 * A[0]} = {A[1]}')
print(f'Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.')
print(f'Первая и вторая строки матрицы A линейнозависимы.')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

Умножим первую строку матрицы A на -2:
-2[-2  7 -3] = [  4 -14   6]

В результате умножения получаем вторую строку матрицы A:
[  4 -14   6] = [  4 -14   6]
Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.
Первая и вторая строки матрицы A линейнозависимы.


#### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Определение__

_Строчным рангом матрицы_ называется максимальное число линейно независимых строк этой матрицы.

_Столбцовым рангом матрицы_ называется максимальное число линейно независимых столбцов этой матрицы.

__Теорема__

_Строчный ранг матрицы всегда совпадает с столбцовым и равен максимальному размеру ее невырожденного минора._

In [13]:
# а)

A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'A:\n{A}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]



In [14]:
print(f'A:\n{A}\n')
print(f'Сложим первую и вторую строки матрицы A:')
print(f'{A[0]} + {A[1]} = {A[0] + A[1]}\n')
print(f'В результате сложения получаем третью строку матрицы A:')
print(f'{A[2]}\n')
print(f'Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.')
print(f'rank(A): 2\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

Сложим первую и вторую строки матрицы A:
[1 2 3] + [1 1 1] = [2 3 4]

В результате сложения получаем третью строку матрицы A:
[2 3 4]

Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.
rank(A): 2



In [15]:
print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

rank(A): 2



In [16]:
# б)

A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'A:\n{A}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]



In [17]:
print(f'A:\n{A}\n')
print(f'Вычтем из третьей строки вторую строку A:')
print(f'{A[2]} - {A[1]} = {A[2] - A[1]}\n')
print(f'В результате вычитания получаем первую строку матрицы A:')
print(f'{A[0]}\n')
print(f'Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.')
print(f'rank(A): 3\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

Вычтем из третьей строки вторую строку A:
[0 0 4 3] - [0 0 2 2] = [0 0 2 1]

В результате вычитания получаем первую строку матрицы A:
[0 0 2 1]

Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.
rank(A): 3



In [18]:
print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

rank(A): 3



#### __5*.__ Написать на Python функцию для нахождения определителя матрицы размера n x n, не используя NumPy.

In [19]:
def matrix_determinant(A):
    try:
        n = len(A)
        m = len(A[0])

        if n == m:            
            if n == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det

            norms = []

            for row in A:
                norm = 0
                for col in row:
                    norm += math.sqrt(math.pow(col, 2))
                norms.append(norm)

            i = 0
            min_norm = norms[0]

            for idx, norm in enumerate(norms[1:], start=1):
                if norm < min_norm:
                    min_norm = norm
                    i = idx
            
            det = 0
            for j in range(m):
                M = [[col for cidx, col in enumerate(row) if cidx != j ] for ridx, row in enumerate(A) if ridx != i]
                sign = (-1) ** ((i + 1 + j + 1) % 2)
                det += sign * A[i][j] * matrix_determinant(M)
                
            return det
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

In [20]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[4 2 3]
 [0 5 1]
 [0 0 9]]

Trial(det(A)): 180
Check(det(A)): 180.0


In [21]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Trial(det(A)): 0
Check(det(A)): -9.51619735392994e-16


In [22]:
A = np.array([[2, 5, 1, 3], [4, 1, 7, 9], [6, 8, 3, 2], [7, 8, 1, 4]])

print(f'A:\n {A}\n')
print(f'Trial(det(A)): {matrix_determinant(A)}')
print(f'Check(det(A)): {np.linalg.det(A)}')

A:
 [[2 5 1 3]
 [4 1 7 9]
 [6 8 3 2]
 [7 8 1 4]]

Trial(det(A)): 630
Check(det(A)): 630.0000000000001
